<a href="https://colab.research.google.com/github/123hawaa/ML-Project/blob/main/FLIGHT_PREDECTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Flight Price Prediction(EDA + Feature Engineering)

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
#this is for instead everytime type plot.show

In [ ]:
df =pd.read_excel('fliht_predction_Data_Train.xlsx')

In [ ]:
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [ ]:
df_test =pd.read_excel('FLIGHT_PREDTION__Test_set.xlsx')

In [ ]:
df_test['type'] = "test"
df['type'] = "train"

In [ ]:
df_final = df.append(df_test)
df_final

<ipython-input-101-f0cb0b0b7108>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_final = df.append(df_test)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,type
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,train
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,train
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0,train
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,train
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,train
...,...,...,...,...,...,...,...,...,...,...,...,...
2666,Air India,6/06/2019,Kolkata,Banglore,CCU → DEL → BLR,20:30,20:25 07 Jun,23h 55m,1 stop,No info,NaN,test
2667,IndiGo,27/03/2019,Kolkata,Banglore,CCU → BLR,14:20,16:55,2h 35m,non-stop,No info,NaN,test
2668,Jet Airways,6/03/2019,Delhi,Cochin,DEL → BOM → COK,21:50,04:25 07 Mar,6h 35m,1 stop,No info,NaN,test
2669,Air India,6/03/2019,Delhi,Cochin,DEL → BOM → COK,04:00,19:15,15h 15m,1 stop,No info,NaN,test
2670,Multiple carriers,15/06/2019,Delhi,Cochin,DEL → BOM → COK,04:55,19:15,14h 20m,1 stop,No info,NaN,test

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Date_of_Journey  13354 non-null  object
 2   Source           13354 non-null  object
 3   Destination      13354 non-null  object
 4   Route            13353 non-null  object
 5   Dep_Time         13354 non-null  object
 6   Arrival_Time     13354 non-null  object
 7   Duration         13354 non-null  object
 8   Total_Stops      13353 non-null  object
 9   Additional_Info  13354 non-null  object
 10  Price            10683 non-null  float64
 11  type             13354 non-null  object
dtypes: float64(1), object(11)
memory usage: 1.3+ MB

WE WANT TO DO DRIVE FEATURE from time feature

In [ ]:
df_final['date'] = df_final['Date_of_Journey'].str.split('/').str[0]
df_final['month'] = df_final['Date_of_Journey'].str.split('/').str[1]
df_final['year'] = df_final['Date_of_Journey'].str.split('/').str[3]

In [ ]:
df_final.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,type,date,month,year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,train,24,03,NaN
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,train,1,05,NaN

In [ ]:
df_final['date']=df_final['date'].astype(int)
df_final['month']=df_final['month'].astype(int)

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Date_of_Journey  13354 non-null  object
 2   Source           13354 non-null  object
 3   Destination      13354 non-null  object
 4   Route            13353 non-null  object
 5   Dep_Time         13354 non-null  object
 6   Arrival_Time     13354 non-null  object
 7   Duration         13354 non-null  object
 8   Total_Stops      13353 non-null  object
 9   Additional_Info  13354 non-null  object
 10  Price            10683 non-null  float64
 11  type             13354 non-null  object
 12  date             13354 non-null  int64
 13  month            13354 non-null  int64
 14  year             0 non-null      float64
dtypes: float64(2), int64(2), object(11)
memory usage: 1.6+ MB

In [ ]:
df_final.drop('Date_of_Journey',axis =1,inplace=True )

In [ ]:
df_final['Arrival_Time'] = df_final['Arrival_Time'].str.split(' ').str[0]

In [ ]:
df_final['Arrival_hour'] = df_final['Arrival_Time'].str.split(':').str[0]
df_final['Arrival_min'] = df_final['Arrival_Time'].str.split(':').str[1]

In [ ]:
df_final.drop('Arrival_Time',axis =1,inplace=True )

In [ ]:
df_final.head(2)

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,type,date,month,year,Arrival_hour,Arrival_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897.0,train,24,3,NaN,01,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662.0,train,1,5,NaN,13,15

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Dep_Time         13354 non-null  object
 5   Duration         13354 non-null  object
 6   Total_Stops      13353 non-null  object
 7   Additional_Info  13354 non-null  object
 8   Price            10683 non-null  float64
 9   type             13354 non-null  object
 10  date             13354 non-null  int64
 11  month            13354 non-null  int64
 12  year             0 non-null      float64
 13  Arrival_hour     13354 non-null  object
 14  Arrival_min      13354 non-null  object
dtypes: float64(2), int64(2), object(11)
memory usage: 1.6+ MB

In [ ]:
df_final['Arrival_hour'] = df_final['Arrival_hour'].astype(int)
df_final['Arrival_min'] = df_final['Arrival_min'].astype(int)

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Dep_Time         13354 non-null  object
 5   Duration         13354 non-null  object
 6   Total_Stops      13353 non-null  object
 7   Additional_Info  13354 non-null  object
 8   Price            10683 non-null  float64
 9   type             13354 non-null  object
 10  date             13354 non-null  int64
 11  month            13354 non-null  int64
 12  year             0 non-null      float64
 13  Arrival_hour     13354 non-null  int64
 14  Arrival_min      13354 non-null  int64
dtypes: float64(2), int64(4), object(9)
memory usage: 1.6+ MB

In [ ]:
df_final['dep_hour'] = df_final['Dep_Time'].str.split(':').str[0]
df_final['dep_min'] = df_final['Dep_Time'].str.split(':').str[1]
df_final['dep_hour'] = df_final['Arrival_hour'].astype(int)
df_final['dep_min'] = df_final['Arrival_min'].astype(int)
df_final.drop('Dep_Time',axis =1,inplace=True )

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Duration         13354 non-null  object
 5   Total_Stops      13353 non-null  object
 6   Additional_Info  13354 non-null  object
 7   Price            10683 non-null  float64
 8   type             13354 non-null  object
 9   date             13354 non-null  int64
 10  month            13354 non-null  int64
 11  year             0 non-null      float64
 12  Arrival_hour     13354 non-null  int64
 13  Arrival_min      13354 non-null  int64
 14  dep_hour         13354 non-null  int64
 15  dep_min          13354 non-null  int64
dtypes: float64(2), int64(6), object(8)
memory usage: 1.7+ MB

In [ ]:
df_final['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [ ]:
df_final['Total_Stops'] =df_final['Total_Stops'].map({'non-stop':0,'1 stop':1,'2 stops':3,'4 stops':4,'nan':1})

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Duration         13354 non-null  object
 5   Total_Stops      13297 non-null  float64
 6   Additional_Info  13354 non-null  object
 7   Price            10683 non-null  float64
 8   type             13354 non-null  object
 9   date             13354 non-null  int64
 10  month            13354 non-null  int64
 11  year             0 non-null      float64
 12  Arrival_hour     13354 non-null  int64
 13  Arrival_min      13354 non-null  int64
 14  dep_hour         13354 non-null  int64
 15  dep_min          13354 non-null  int64
dtypes: float64(3), int64(6), object(7)
memory usage: 1.7+ MB

In [ ]:
df_final.drop('Route',axis = 1,inplace=True)

In [ ]:
df_final['Duration'] = df_final['Duration'].str[0]

In [ ]:
df_final['Duration'] = df_final['Duration'].astype(int)

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Duration         13354 non-null  int64
 4   Total_Stops      13297 non-null  float64
 5   Additional_Info  13354 non-null  object
 6   Price            10683 non-null  float64
 7   type             13354 non-null  object
 8   date             13354 non-null  int64
 9   month            13354 non-null  int64
 10  year             0 non-null      float64
 11  Arrival_hour     13354 non-null  int64
 12  Arrival_min      13354 non-null  int64
 13  dep_hour         13354 non-null  int64
 14  dep_min          13354 non-null  int64
dtypes: float64(3), int64(7), object(5)
memory usage: 1.6+ MB

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder= LabelEncoder()

In [ ]:
df_final['Airline']=labelencoder.fit_transform(df_final['Airline'])
df_final['Source']=labelencoder.fit_transform(df_final['Source'])
df_final['Destination']=labelencoder.fit_transform(df_final['Destination'])
df_final['Additional_Info']=labelencoder.fit_transform(df_final['Additional_Info'])

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13354 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  int64
 1   Source           13354 non-null  int64
 2   Destination      13354 non-null  int64
 3   Duration         13354 non-null  int64
 4   Total_Stops      13297 non-null  float64
 5   Additional_Info  13354 non-null  int64
 6   Price            10683 non-null  float64
 7   type             13354 non-null  object
 8   date             13354 non-null  int64
 9   month            13354 non-null  int64
 10  year             0 non-null      float64
 11  Arrival_hour     13354 non-null  int64
 12  Arrival_min      13354 non-null  int64
 13  dep_hour         13354 non-null  int64
 14  dep_min          13354 non-null  int64
dtypes: float64(3), int64(11), object(1)
memory usage: 1.6+ MB

SPLIT DATA INTO TRAIN AND TEST

In [ ]:
train = df_final[df_final['type'] == "train"]

test = df_final[df_final['type'] == "test"]

In [ ]:
train.drop(['type'],axis = 1,inplace = True)

<ipython-input-128-669d3fd45cf9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train.drop(['type'],axis = 1,inplace = True)

In [ ]:
test.drop(['type','Price'],axis = 1,inplace = True)

<ipython-input-129-68a78787e3de>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test.drop(['type','Price'],axis = 1,inplace = True)

In [ ]:
train.shape

(10683, 14)

In [ ]:
test.shape

(2671, 13)

In [ ]:
train

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,date,month,year,Arrival_hour,Arrival_min,dep_hour,dep_min
0,3,0,5,2,0.0,8,3897.0,24,3,NaN,1,10,1,10
1,1,3,0,7,3.0,8,7662.0,1,5,NaN,13,15,13,15
2,4,2,1,1,3.0,8,13882.0,9,6,NaN,4,25,4,25
3,3,3,0,5,1.0,8,6218.0,12,5,NaN,23,30,23,30
4,3,0,5,4,1.0,8,13302.0,1,3,NaN,21,35,21,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,0,3,0,2,0.0,8,4107.0,9,4,NaN,22,25,22,25
10679,1,3,0,2,0.0,8,4145.0,27,4,NaN,23,20,23,20
10680,4,0,2,3,0.0,8,7229.0,27,4,NaN,11,20,11,20
10681,10,0,5,2,0.0,8,12648.0,1,3,NaN,14,10,14,10
10682,1,2,1,8,3.0,8,11753.0,9,5,NaN,19,15,19,15

In [ ]:
#X = train.iloc[:, :-1]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test = train_test_split(train , test_size = 0.2 , random_state = 11)
df_train , df_val = train_test_split(x_train, test_size = 0.25 , random_state =11)
df_train = df_train.reset_index(drop=True)

x_test = x_test.reset_index(drop = True)

In [ ]:
y_train= df_train.Price
y_test = x_test.Price

In [ ]:
y_train

0       11432.0
1       12778.0
2        6628.0
3        5530.0
4        4937.0
         ...
6404     6442.0
6405     3419.0
6406    14300.0
6407     6442.0
6408     9397.0
Name: Price, Length: 6409, dtype: float64

In [ ]:
del x_train['Price']
del x_test['Price']

WE WANT TO DO DRIVE FEATURE from time feature